version: '2' 

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    env_file:
      - ./hadoop/hadoop.env
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - shared_network

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    depends_on: 
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop/hadoop.env
    networks:
      - shared_network

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    depends_on: 
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop/hadoop.env
    networks:
      - shared_network
  
  hue:
    image: gethue/hue:20201111-135001
    hostname: hue
    container_name: hue
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    volumes:
      - ./hue/conf.dist:/usr/share/hue/desktop/conf
    depends_on: 
      - namenode
    networks:
      - shared_network

  nifi:
    image: apache/nifi:1.15.3
    container_name: nifi
    ports:
      - "8443:8443"
    volumes:
      - ./data/:/tmp/data/
      - ./nifi/hdfs/core-site.xml:/opt/nifi/nifi-current/conf/core-site.xml
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
    env_file:
      - ./nifi/nifi.env
    networks:
      - shared_network

  nifi-registry:
    image: apache/nifi-registry:1.15.3
    container_name: nifi-registry
    ports:
      - "18080:18080"
    volumes:
      - nifi_registry:/opt/nifi-registry/nifi-registry-current/
    networks:
      - shared_network

  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
      - "2222:22"
    env_file:
      - ./spark/spark.env
    volumes: 
      - ./spark/scripts:/opt/bitnami/spark/jobs
    networks:
      - shared_network

  spark-worker1:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    env_file:
      - ./spark/spark.env
    volumes: 
      - ./spark/scripts:/opt/bitnami/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - shared_network

  spark-worker2:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    env_file:
      - ./spark/spark.env
    volumes: 
      - ./spark/scripts:/opt/bitnami/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - shared_network

  spark-worker3:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-worker3
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    env_file:
      - ./spark/spark.env
    volumes: 
      - ./spark/scripts:/opt/bitnami/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - shared_network

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/scripts:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
    networks:
      - shared_network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8083:8081"
    env_file:
      - ./mongodb/mongodb.env
    networks:
      - shared_network

  postgres:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shared_network
    restart: always

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    env_file:
      - ./airflow/airflow.env
    volumes:
      - ./airflow/data/dags:/opt/airflow/dags
      - ./airflow/data/logs:/opt/airflow/logs
      - ./airflow/data/db:/opt/airflow/db
    command: bash -c "airflow db init && python /opt/airflow/init_ssh_connection.py && airflow db init && airflow webserver"
    depends_on:
      - airflow-scheduler
      - postgres
    networks:
      - shared_network

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    env_file:
      - ./airflow/airflow.env
    volumes:
      - ./airflow/data/dags:/opt/airflow/dags
      - ./airflow/data/logs:/opt/airflow/logs
      - ./airflow/data/db:/opt/airflow/db
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Yusuf --lastname Ganiyu --role Admin --email airscholar@gmail.com --password admin && airflow scheduler"
    depends_on:
      - postgres
    networks:
      - shared_network

  metabase:
    image: metabase/metabase:v0.53.x
    container_name: metabase
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./metabase/metabase_data/:/metabase-data
    env_file:
      - ./metabase/metabase.env
    networks:
      - shared_network

volumes:
  hadoop_namenode: {}
  hadoop_datanode1: {}
  hadoop_datanode2: {}
  nifi_conf: {}
  nifi_database_repository: {}
  nifi_flowfile_repository: {}
  nifi_content_repository: {}
  nifi_provenance_repository: {}
  nifi_state: {}
  nifi_registry: {}
  mongodb_data: {}
  postgres_data: {}

networks:
  shared_network:
    driver: bridge