version: '2' 

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    env_file:
      - ./hadoop/hadoop.env
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - shared_network

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    depends_on: 
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop/hadoop.env
    networks:
      - shared_network

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    depends_on: 
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop/hadoop.env
    networks:
      - shared_network
  
  hue:
    image: gethue/hue:20201111-135001
    hostname: hue
    container_name: hue
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    volumes:
      - ./hue/conf.dist:/usr/share/hue/desktop/conf
    depends_on: 
      - namenode
    networks:
      - shared_network

  nifi:
    image: apache/nifi:1.15.3
    container_name: nifi
    ports:
      - "8443:8443"
    volumes:
      - ./data/:/tmp/data/
      - ./nifi/hdfs/core-site.xml:/opt/nifi/nifi-current/conf/core-site.xml
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
    env_file:
      - ./nifi/nifi.env
    networks:
      - shared_network

  nifi-registry:
    image: apache/nifi-registry:1.15.3
    container_name: nifi-registry
    ports:
      - "18080:18080"
    volumes:
      - nifi_registry:/opt/nifi-registry/nifi-registry-current/
    networks:
      - shared_network

  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./spark/spark.env
    volumes: 
      - ./spark/scripts:/home/scripts
    networks:
      - shared_network

  spark-worker1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    env_file:
      - ./spark/spark.env
    networks:
      - shared_network
  
  spark-worker2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker2
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    env_file:
      - ./spark/spark.env
    networks:
      - shared_network

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/scripts:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
    networks:
      - shared_network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8083:8081"
    env_file:
      - ./mongodb/mongodb.env
    networks:
      - shared_network

  metabase:
    image: metabase/metabase:v0.53.x
    container_name: metabase
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./metabase/data:/metabase-data
    env_file:
      - ./metabase/metabase.env
    networks:
      - shared_network

volumes:
  hadoop_namenode: {}
  hadoop_datanode1: {}
  hadoop_datanode2: {}
  nifi_conf: {}
  nifi_database_repository: {}
  nifi_flowfile_repository: {}
  nifi_content_repository: {}
  nifi_provenance_repository: {}
  nifi_state: {}
  nifi_registry: {}
  mongodb_data: {}

networks:
  shared_network:
    driver: bridge